name: CI workflow

#event
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#job - collection of steps
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

